# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  vote:
    image: acrkshyvetskyi.azurecr.io/vote:latest
    pull_policy: always
    # depends_on:
    #   redis:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - "8080:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: acrkshyvetskyi.azurecr.io/result:latest
    pull_policy: always
    # depends_on:
    #   db:
    #     condition: service_healthy
    ports:
      - "8081:80"
    networks:
      - front-tier
      - back-tier

  worker:
    image: acrkshyvetskyi.azurecr.io/worker:latest
    pull_policy: always
    # depends_on:
    #   redis:
    #     condition: service_healthy
    #   db:
    #     condition: service_healthy
    networks:
      - back-tier

  # redis:
  #   image: redis:alpine
  #   volumes:
  #     - "./healthchecks:/healthchecks"
  #   healthcheck:
  #     test: /healthchecks/redis.sh
  #     interval: "5s"
  #   networks:
  #     - back-tier

  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "postgres"
  #   volumes:
  #     - "db-data:/var/lib/postgresql/data"
  #     - "./healthchecks:/healthchecks"
  #   healthcheck:
  #     test: /healthchecks/postgres.sh
  #     interval: "5s"
  #   networks:
  #     - back-tier

  # seed:
  #   build: ./seed-data
  #   profiles: ["seed"]
  #   depends_on:
  #     vote:
  #       condition: service_healthy
  #   networks:
  #     - front-tier
  #   restart: "no"

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
